### PR TITLE
Fix uuoc (Useless use of ''cat'' from frontpage)

### PR DESCRIPTION
**Pull request by ghost**
http://partmaps.org/era/unix/award.html

### CODE REVIEW

**Comment by haneefmubarak** [comment]
@joshcartwright It helps those who just use the shell (and therefore may not be familiar with `curl`) understand what it going on.

**Comment by haneefmubarak** [comment]
@rupa I vote to close without merging.

**Comment by ghost** [comment]
I'm honestly not that opinionated about this change, and am okay with dropping it... :)

However, @haneefmubarak , using '<' to for redirection _is_ a feature of the shell, and not a feature of curl, so I think that invalidates your argument.

**Comment by haneefmubarak** [comment]
Oh. Didn't see the < (never really learned the HTML bs). Still, most newbies still find piping a lot easier then file IO redirection, and when you start to stack it heavily, file IO redirection can get a bit confusing, whereas piping is still relatively straightforward (always left to right, code goes into next program, etc.)...

**Comment by rupa** [comment]
This _is_ a UUOC, but the intent is just to show how to use the thing, and eliminating it obscures that a bit, IMHO. I considered switching the example to `ls` but that's silly too :smile:

**Comment by haneefmubarak** [comment]
`ls`?

You sir, have made a dangerous move. You have piqued my curiosity. How would you use `ls` in the example?

**Comment by ghost** [comment]
@haneefmubarak Presumably just as `ls | <curl command>`

@rupa Thanks for at least giving the UUOC a thought :)

**Pull request closed without merging**
